/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_syeyoung_dungeonsguide_mod_dungeon_roomprocessor_waterpuzzle_Waterboard */

#ifndef _Included_kr_syeyoung_dungeonsguide_mod_dungeon_roomprocessor_waterpuzzle_Waterboard
#define _Included_kr_syeyoung_dungeonsguide_mod_dungeon_roomprocessor_waterpuzzle_Waterboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_syeyoung_dungeonsguide_mod_dungeon_roomprocessor_waterpuzzle_Waterboard
 * Method:    nativeSolve
 * Signature: (DDI)[Lkr/syeyoung/dungeonsguide/mod/dungeon/roomprocessor/waterpuzzle/Waterboard/Action;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_syeyoung_dungeonsguide_mod_dungeon_roomprocessor_waterpuzzle_Waterboard_nativeSolve
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
